### ISSUE TITLE
Send empty message to separate messages that begin with a blank line

### ISSUE THREAD

**Issue by DerpyChap** [lolPants/discord-welcome-action#2]
~~Currently when splitting messages using horizontal rules (`---`) with a trailing blank line, the Action will add the Unicode character `U+1CBC` to the start of the next message to ensure the blank line is retained at the start of the next message. However, on Discord Mobile this Unicode character renders as a broken character.~~

apparently we just manually inserted that into our welcome readme file lol nvm

Instead of adding this character to the start of the next message, a new blank message could be sent in its place that sits between the two messages. This can be done by sending a message with just an embed, and then supressing the embed. This will ensure that no broken character is shown on mobile and that the line break is kept in the overall formatting of the channel.

**Comment by luludotdev** [comment]
Closed as of d5ec0d2508aed2d13b0c5ad052cceb51f6849d02
